Algoritmo "Variaceis"
//  
//  
// Disciplina  : Algoritmos e lógica I
// Aula        : Varisveis
// Descrição   : Demonstrar as variaveis
// Autor(a)    : Carlos Borba
// Data atual  : 29/9/2021
Var
// Seção de Declarações das variáveis 
//primeiro nome
//segundo nome
//idade
//cidade
//endreco

         primeiroNome, segundoNome, cidade, endereco: caractere
         idade: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo